# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: ToDevOps
    url: https://github.com/todevops


# navigation menu
menu:
  - name: 主页
    slug: home
    url: /
  - name: 归档
    slug: archives
    url: /archives
  - name: 关于
    slug: about
    url: /about

# widgets
widgets:
  # - about
  - categories
  - tags
  - links

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/todevops
# - slug: rss
# 	url: /atom.xml
